import { createDefaultCompressor, createDefaultEqState, createId } from "../../daw/model/Project";
import type { BuiltinPluginId, PluginCpuCost, PluginDescriptor, PluginInstance, PluginTargetKind } from "../../daw/model/Plugin";
import { applyPluginQualityGuards } from "./pluginQualityGuards";

export const BUILTIN_PLUGINS: PluginDescriptor[] = [
  {
    id: "sweet-parametric-eq",
    name: "Sweet Parametric EQ",
    shortName: "EQ",
    category: "eq",
    description: "8-band mobile parametric EQ backed by Web Audio BiquadFilterNode.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: false,
    createDefaultParams: () => createDefaultEqState() as unknown as Record<string, unknown>,
  },
  {
    id: "sweet-character",
    name: "Sweet Character",
    shortName: "Tone",
    category: "saturation",
    description: "Mobile-safe tone transformation for punchy drums, tighter bass, and more altered synth stems.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: false,
    createDefaultParams: () => ({
      enabled: false,
      mode: "synthTransform",
      amount: 0.45,
      tone: 0.55,
      mix: 0.3,
    }),
  },
  {
    id: "sweet-compressor",
    name: "Sweet Compressor",
    shortName: "Comp",
    category: "dynamics",
    description: "Track/master dynamics control using DynamicsCompressorNode with makeup gain.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: false,
    createDefaultParams: () => createDefaultCompressor(false) as unknown as Record<string, unknown>,
  },
  {
    id: "sweet-limiter",
    name: "Sweet Limiter",
    shortName: "Limit",
    category: "dynamics",
    description: "Master safety limiter for mobile mixdown export.",
    supportedTargets: ["master"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: false,
    createDefaultParams: () => ({
      threshold: -1,
      release: 0.06,
    }),
  },
  {
    id: "sweet-filter",
    name: "Sweet Filter",
    shortName: "Filter",
    category: "eq",
    description: "Single mobile-safe Biquad filter for quick tone cuts, sweeps, and cleanup.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      type: "lowpass",
      frequency: 12000,
      q: 0.8,
      gainDb: 0,
    }),
  },
  {
    id: "sweet-tilt-eq",
    name: "Sweet Tilt EQ",
    shortName: "Tilt",
    category: "eq",
    description: "Broad master/track balance EQ. Tilts lows and highs around a pivot without surgical band edits.",
    supportedTargets: ["track", "master"],
    recommendedFor: ["music", "loop", "synth", "keys", "other"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      tiltDb: 0,
      pivotHz: 1000,
      lowShape: 0.7,
      highShape: 0.7,
      mix: 1,
      outputDb: 0,
    }),
  },
  {
    id: "sweet-drive",
    name: "Sweet Drive",
    shortName: "Drive",
    category: "saturation",
    description: "Light WaveShaper saturation for harder drums, bass, and synth color.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      drive: 0.35,
      tone: 0.55,
      mix: 0.35,
    }),
  },
  {
    id: "sweet-saturator",
    name: "Sweet Saturator",
    shortName: "Sat",
    category: "saturation",
    description: "Essential analog-style saturation for gentle harmonics, density, and perceived loudness without harsh clipping.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      drive: 0.22,
      color: 0.48,
      lowCutHz: 35,
      mix: 0.18,
      outputDb: 0,
    }),
  },
  {
    id: "sweet-clipper",
    name: "Sweet Clipper",
    shortName: "Clip",
    category: "dynamics",
    description: "Mobile-safe soft clipper for peak shaping before limiter gain. Keeps attack while reducing limiter stress.",
    supportedTargets: ["track", "master"],
    recommendedFor: ["drums", "bass", "music", "loop", "other"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      mode: "soft",
      driveDb: 2,
      ceilingDb: -1,
      knee: 0.45,
      hardness: 0.45,
      mix: 0.65,
      outputDb: -0.3,
      autoTrim: true,
    }),
  },
  {
    id: "sweet-peak-maximizer",
    name: "Sweet Peak Maximizer",
    shortName: "PeakMax",
    category: "dynamics",
    description: "Master-only peak maximizer. Preview stays light, while WAV export uses an offline lookahead peak pass with true-peak guard.",
    supportedTargets: ["master"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "medium",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      preset: "Clean Lift",
      mode: "clean",
      inputDriveDb: 2,
      ceilingDb: -1,
      lookaheadMs: 2,
      releaseMs: 90,
      transientProtect: 0.65,
      stereoLink: 1,
      softClipGuard: 0.18,
      truePeakGuard: true,
      oversample: "4x",
      autoDrive: false,
      targetLufs: -10,
      maxAutoDriveDb: 6,
    }),
  },
  {
    id: "sweet-low-end-translator",
    name: "Sweet Low-End Translator",
    shortName: "Low+",
    category: "saturation",
    description: "Creates audible bass harmonics around 80-250Hz instead of boosting risky 20-60Hz sub energy.",
    supportedTargets: ["track"],
    recommendedFor: ["bass", "music", "loop", "other"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      mode: "subToBass",
      amount: 0.24,
      drive: 0.16,
      sourceLowHz: 58,
      translateHz: 115,
      upperHarmonicHz: 185,
      lowCutHz: 30,
      subGuardHz: 55,
      subGuardDb: -0.7,
      mix: 0.16,
      outputDb: -0.4,
      monoSafe: true,
    }),
  },
  {
    id: "sweet-air-exciter",
    name: "Sweet Air Exciter",
    shortName: "Air",
    category: "saturation",
    description: "AIMIX-safe ultra-high air generator that adds a thin 10kHz-18kHz sheen with harshness guard and no low-mid buildup.",
    supportedTargets: ["track", "master"],
    recommendedFor: ["drums", "backingVocal", "guitar", "synth", "keys", "music", "fx", "other"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      amount: 0.22,
      tone: 0.62,
      focusHz: 12500,
      highPassHz: 6800,
      postHighPassHz: 10000,
      lowPassHz: 18500,
      harshGuard: 0.74,
      syntheticAirBed: false,
      airBedLevel: 0,
      airBedKeyHz: 3200,
      airBedFollow: 0.72,
      dryLevel: 1,
      mix: 0.06,
      outputDb: -1,
    }),
  },
  {
    id: "sweet-aimix-glow",
    name: "AIMIX Glow",
    shortName: "Glow",
    category: "vocal",
    description: "Track insert version of AIMIX Glow: vocal clarity, harmonic gloss, safe air, and de-harsh without adding a constant noise bed.",
    supportedTargets: ["track"],
    recommendedFor: ["vocal", "backingVocal", "synth", "keys", "music", "other"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      preset: "AI Stem Rescue",
      amount: 42,
      recover: 34,
      gloss: 22,
      air: 18,
      tame: 55,
      mix: 0.32,
      outputDb: -0.3,
    }),
  },
  {
    id: "sweet-utility",
    name: "Sweet Utility",
    shortName: "Util",
    category: "utility",
    description: "Essential gain and mono-width utility for level matching, center checking, and safe mobile mix decisions.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      gainDb: 0,
      width: 1,
      mono: false,
    }),
  },
  {
    id: "sweet-delay-lite",
    name: "Sweet Delay Lite",
    shortName: "Delay",
    category: "space",
    description: "Small-footprint DelayNode echo with feedback and wet mix.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    memoryCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      timeSec: 0.25,
      feedback: 0.25,
      mix: 0.18,
    }),
  },
  {
    id: "sweet-reverb-lite",
    name: "Sweet Reverb Lite",
    shortName: "Reverb",
    category: "space",
    description: "Mobile-safe depth reverb with pre-delay, low cut, high cut, width, and wet mix.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "medium",
    memoryCost: "medium",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      mode: "room",
      room: 0.32,
      damp: 0.62,
      preDelayMs: 18,
      decaySec: 0.65,
      lowCutHz: 180,
      highCutHz: 9000,
      width: 0.32,
      ducking: 0.18,
      mix: 0.07,
    }),
  },
  {
    id: "sweet-guitar-fx",
    name: "Sweet Guitar FX",
    shortName: "Guitar",
    category: "guitar",
    description: "Legacy all-in-one amp-like drive and cabinet tone. New projects can use Drive/Amp/Cab/Rig blocks.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "medium",
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      drive: 0.48,
      tone: 0.45,
      body: 0.55,
      mix: 0.45,
    }),
  },
  {
    id: "sweet-guitar-drive",
    name: "Sweet Guitar Drive",
    shortName: "G Drive",
    category: "guitar",
    description: "First-stage pick/drive block for guitar, bass, drums, and synth stems.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      drive: 0.42,
      tone: 0.52,
      mix: 0.4,
    }),
  },
  {
    id: "sweet-guitar-amp",
    name: "Sweet Guitar Amp",
    shortName: "Amp",
    category: "guitar",
    description: "Amp voicing block with drive, tone, body, and parallel mix.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "medium",
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      drive: 0.5,
      tone: 0.48,
      body: 0.56,
      mix: 0.5,
    }),
  },
  {
    id: "sweet-guitar-cab",
    name: "Sweet Guitar Cab",
    shortName: "Cab",
    category: "guitar",
    description: "Cabinet/room block using generated mobile-safe convolution tones.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "high",
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      preset: "Small Combo Cab",
      irType: "smallComboCab",
      preDelayMs: 0,
      tone: 0.52,
      body: 0.5,
      width: 0.18,
      mix: 0.52,
    }),
  },
  {
    id: "sweet-guitar-rig",
    name: "Sweet Guitar Rig",
    shortName: "Rig",
    category: "guitar",
    description: "Full rhythm-guitar rig: chopping, pick attack, amp color, cab body, and gate.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "high",
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      preset: "Clean Cutting Guitar",
      mode: "cutting",
      chopEnabled: true,
      chopRate: "1/16",
      pickAttack: 0.65,
      muteTightness: 0.82,
      ampDrive: 0.18,
      cabinet: "cleanCombo",
      body: 0.42,
      brightness: 0.62,
      noiseGate: 0.35,
      mix: 0.95,
    }),
  },
  {
    id: "sweet-vocal-fx",
    name: "Sweet Vocal FX",
    shortName: "Vocal",
    category: "saturation",
    description: "Vocal clarity color with restrained drive, body, presence, air, and smoothing.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      drive: 0.14,
      body: 0.48,
      presence: 0.52,
      air: 0.46,
      mix: 0.1,
    }),
  },
  {
    id: "sweet-bass-enhancer",
    name: "Sweet Bass Translator",
    shortName: "Bass T",
    category: "saturation",
    description: "Bass audibility translator with sub guard, harmonics, tightness, tone, and wet mix.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      sub: 0.22,
      harmonics: 0.46,
      tight: 0.56,
      tone: 0.44,
      mix: 0.24,
    }),
  },
  {
    id: "sweet-parallel-comp",
    name: "Sweet Parallel Comp",
    shortName: "PCOMP",
    category: "dynamics",
    description: "Parallel compressor for density while keeping the original attack and natural tone.",
    supportedTargets: ["track"],
    recommendedFor: ["vocal", "backingVocal", "drums", "bass", "guitar", "synth", "keys", "music", "loop"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      preset: "Glue Light",
      mix: 0.12,
      crush: 34,
      attackMs: 24,
      releaseMs: 180,
      tone: -12,
      outputDb: 0,
      wetHpfHz: 100,
      wetLpfHz: 11000,
      autoGain: true,
    }),
  },
  {
    id: "sweet-vocal-duck-eq",
    name: "Sweet Vocal Duck EQ",
    shortName: "VDuck",
    category: "dynamics",
    description: "Level-following 2.5kHz vocal-space duck for accompaniment tracks. It only reduces the band while lead or backing vocals are active.",
    supportedTargets: ["track"],
    recommendedFor: ["music", "guitar", "synth", "keys", "loop", "fx", "other"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      frequencyHz: 2500,
      q: 1.1,
      maxReductionDb: 1.6,
      threshold: 0.035,
      attackMs: 35,
      releaseMs: 180,
      mix: 1,
      lookaheadMs: 0,
    }),
  },
  {
    id: "sweet-de-esser",
    name: "Sweet De-Esser",
    shortName: "DeEss",
    category: "dynamics",
    description: "Light sibilance reduction around the harsh 5kHz-10kHz vocal range.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      frequency: 7200,
      amount: 0.3,
      sharpness: 0.55,
      mix: 0.35,
    }),
  },
  {
    id: "sweet-gate-lite",
    name: "Sweet Gate Lite",
    shortName: "Gate",
    category: "dynamics",
    description: "Simple noise-gate style cleanup using a mobile-safe wave-shaping gate.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      threshold: 0.12,
      floor: 0.18,
      softness: 0.55,
      mix: 0.8,
    }),
  },
  {
    id: "sweet-chorus",
    name: "Sweet Chorus",
    shortName: "Chorus",
    category: "modulation",
    description: "Classic modulated-delay chorus for vocals, guitars, pads, and synth stems.",
    supportedTargets: ["track", "master"],
    latencySec: 0.03,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      rate: 0.28,
      depth: 0.42,
      feedback: 0.18,
      mix: 0.28,
    }),
  },
  {
    id: "sweet-phaser",
    name: "Sweet Phaser",
    shortName: "Phaser",
    category: "modulation",
    description: "All-pass sweep phaser for guitars, drums, keys, and synth movement.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      rate: 0.32,
      depth: 0.45,
      feedback: 0.22,
      mix: 0.35,
    }),
  },
  {
    id: "sweet-stereo-widener",
    name: "Sweet Stereo Widener",
    shortName: "Width",
    category: "utility",
    description: "Short stereo delay spread for wider hooks, pads, guitars, and backing vocals.",
    supportedTargets: ["track", "master"],
    latencySec: 0.02,
    mobileSafe: true,
    cpuCost: "low",
    memoryCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      width: 0.22,
      delayMs: 8,
      tone: 0.56,
      mix: 0.16,
    }),
  },
  {
    id: "sweet-support-widener",
    name: "Sweet Support Widener",
    shortName: "S.Width",
    category: "utility",
    description: "AIMIX-safe high-side width for support stems; low band stays mono-safe.",
    supportedTargets: ["track"],
    recommendedFor: ["backingVocal", "guitar", "synth", "keys", "music", "loop", "fx", "other"],
    latencySec: 0.02,
    mobileSafe: true,
    cpuCost: "low",
    memoryCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      width: 0.08,
      mix: 0.08,
      delayMs: 7,
      highPassHz: 2500,
      lowPassHz: 16000,
      lowMonoHz: 120,
      tone: 0.58,
      monoSafety: true,
    }),
  },
  {
    id: "sweet-transient-shaper",
    name: "Sweet Transient Shaper",
    shortName: "Trans",
    category: "dynamics",
    description: "Attack and sustain shaping for punchier drums, plucks, loops, and one-shots.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      attack: 0.48,
      sustain: 0.34,
      tone: 0.55,
      mix: 0.5,
    }),
  },
  {
    id: "sweet-rhythm-chopper",
    name: "Sweet Rhythm Chopper",
    shortName: "Chop",
    category: "transform",
    description: "Tempo-synced rhythmic gate for cutting, stutter, pulse, and guitar-like chops.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      preset: "Tight 16th Cutting",
      rate: "1/16",
      pattern: "upDownMute",
      depth: 0.85,
      attackMs: 4,
      releaseMs: 35,
      swing: 0.03,
      humanize: 0.03,
      accent: 0.35,
      mix: 1,
    }),
  },
  {
    id: "sweet-guitarizer",
    name: "Sweet Guitarizer",
    shortName: "Gtrz",
    category: "transform",
    description: "Transforms chord or guitar stems toward cutting rhythm guitar with amp/cab color.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      preset: "Clean Cutting Guitar",
      mode: "cutting",
      chopEnabled: true,
      chopRate: "1/16",
      pickAttack: 0.65,
      muteTightness: 0.82,
      ampDrive: 0.18,
      cabinet: "cleanCombo",
      body: 0.42,
      brightness: 0.62,
      noiseGate: 0.35,
      mix: 0.95,
    }),
  },
  {
    id: "sweet-vocal-formant-color",
    name: "Sweet Vocal Formant Color",
    shortName: "Formant",
    category: "vocal",
    description: "Parallel formant-style vocal color using filters, delay color, saturation, and artifact guard.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      preset: "Dark Male-ish",
      pitchSemi: -4,
      formantColor: -0.45,
      body: 0.65,
      throat: 0.55,
      air: 0.18,
      presence: 0.35,
      saturation: 0.22,
      artifactGuard: 0.8,
      mix: 0.82,
    }),
  },
  {
    id: "sweet-ir-space",
    name: "Sweet IR Cabinet / Space",
    shortName: "IR",
    category: "cabinet",
    description: "Generated Convolver cabinet, phone speaker, room, and plate spaces.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "high",
    memoryCost: "high",
    realtimeSafe: false,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      preset: "Small Combo Cab",
      irType: "smallComboCab",
      preDelayMs: 0,
      tone: 0.52,
      body: 0.5,
      width: 0.2,
      mix: 0.55,
    }),
  },
  {
    id: "sweet-vocoder-lite",
    name: "Sweet Vocoder Lite",
    shortName: "Vocoder",
    category: "modulation",
    description: "Robotic carrier color using a native oscillator, formant filters, and parallel wet mix.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "high",
    memoryCost: "low",
    realtimeSafe: false,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      carrierHz: 110,
      formant: 0.55,
      robot: 0.5,
      mix: 0.32,
    }),
  },
  {
    id: "sweet-pitch-assist",
    name: "Sweet Pitch Assist",
    shortName: "Pitch",
    category: "modulation",
    description: "Pitch-tightening style gloss using short modulated delays; not full pitch correction.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "medium",
    memoryCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      amount: 0.38,
      color: 0.62,
      mix: 0.28,
    }),
  },
  {
    id: "sweet-granular-texture",
    name: "Sweet Granular Texture",
    shortName: "Grain",
    category: "modulation",
    description: "Lightweight shimmer and grain-like repeats using staggered delays and filtering.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "high",
    memoryCost: "medium",
    realtimeSafe: false,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      size: 0.36,
      spray: 0.42,
      texture: 0.55,
      mix: 0.24,
    }),
  },
  {
    id: "sweet-multiband-comp",
    name: "Sweet Multiband Comp",
    shortName: "MB Comp",
    category: "dynamics",
    description: "Three-band compressor for stronger drums, safer masters, and stem cleanup.",
    supportedTargets: ["track", "master"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "medium",
    memoryCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      low: 0.35,
      mid: 0.3,
      high: 0.28,
      makeupDb: 0,
      mix: 0.35,
    }),
  },
  {
    id: "sweet-wavetable-carrier",
    name: "Sweet Wavetable Carrier",
    shortName: "Wave",
    category: "instrument",
    description: "Parallel oscillator carrier layer for synth-like color without replacing the source.",
    supportedTargets: ["track"],
    latencySec: 0,
    mobileSafe: true,
    cpuCost: "medium",
    memoryCost: "low",
    realtimeSafe: true,
    external: false,
    insertable: true,
    createDefaultParams: () => ({
      wave: "sawtooth",
      frequency: 110,
      sub: 0.2,
      tone: 0.58,
      mix: 0.25,
    }),
  },
];

export function getPluginsForTarget(target: PluginTargetKind) {
  if (target === "clip") {
    return BUILTIN_PLUGINS.filter((plugin) => plugin.insertable && plugin.supportedTargets.includes("track"));
  }
  return BUILTIN_PLUGINS.filter((plugin) => plugin.supportedTargets.includes(target));
}

export function getFixedPluginsForTarget(target: PluginTargetKind) {
  return getPluginsForTarget(target).filter((plugin) => !plugin.insertable);
}

export function getInsertablePluginsForTarget(target: PluginTargetKind) {
  return getPluginsForTarget(target).filter((plugin) => plugin.insertable);
}

export function getPluginDescriptor(id: BuiltinPluginId) {
  return BUILTIN_PLUGINS.find((plugin) => plugin.id === id) ?? null;
}

export function getPluginCpuCost(id: BuiltinPluginId): PluginCpuCost {
  const descriptor = getPluginDescriptor(id);
  if (descriptor?.cpuCost) {
    return descriptor.cpuCost;
  }

  if (
    id === "sweet-ir-space" ||
    id === "sweet-vocoder-lite" ||
    id === "sweet-granular-texture" ||
    id === "sweet-guitarizer" ||
    id === "sweet-guitar-rig"
  ) {
    return "high";
  }

  if (
    id === "sweet-saturator" ||
    id === "sweet-utility" ||
    id === "sweet-reverb-lite" ||
    id === "sweet-chorus" ||
    id === "sweet-phaser" ||
    id === "sweet-multiband-comp" ||
    id === "sweet-wavetable-carrier" ||
    id === "sweet-guitar-fx" ||
    id === "sweet-guitar-amp"
  ) {
    return "medium";
  }

  return "low";
}

export function getPluginCpuScore(id: BuiltinPluginId) {
  const cost = getPluginCpuCost(id);
  if (cost === "high") return 3;
  if (cost === "medium") return 2;
  return 1;
}

export function estimatePluginChainCpuScore(chain: PluginInstance[]) {
  return chain.reduce((score, plugin) => score + (plugin.enabled ? getPluginCpuScore(plugin.pluginId) : 0), 0);
}

export function getPluginCpuLabel(score: number) {
  if (score >= 8) return "High";
  if (score >= 4) return "Medium";
  return "Low";
}

export function createPluginInstance(pluginId: BuiltinPluginId, target: PluginTargetKind): PluginInstance {
  const descriptor = getPluginDescriptor(pluginId);
  if (!descriptor) {
    throw new Error(`Unknown plug-in: ${pluginId}`);
  }

  const supported = descriptor.supportedTargets.includes(target) || (target === "clip" && descriptor.insertable && descriptor.supportedTargets.includes("track"));
  if (!supported) {
    throw new Error(`${descriptor.name} does not support ${target}.`);
  }

  const now = new Date().toISOString();
  const instance: PluginInstance = {
    id: createId("plugin"),
    pluginId,
    name: descriptor.name,
    enabled: true,
    target,
    params: descriptor.createDefaultParams(),
    createdAt: now,
    updatedAt: now,
  };
  return applyPluginQualityGuards(instance).instance;
}
